name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create and configure config file
        run: |
          mkdir -p js
          cp js/config.template.js js/config.js
          sed -i "s/YOUR_GA_ID/${{ secrets.GOOGLE_ANALYTICS_ID }}/g" js/config.js
          sed -i "s/YOUR_VERIFICATION_CODE/${{ secrets.GOOGLE_SITE_VERIFICATION }}/g" js/config.js
          sed -i "s|YOUR_FORMSPREE_ENDPOINT|https://formspree.io/f/${{ secrets.FORMSPREE_FORM_ID }}|g" js/config.js
          sed -i "s/YOUR_FORMSPREE_ID/${{ secrets.FORMSPREE_FORM_ID }}/g" js/config.js

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: dist
          clean: true
          clean-exclude: |
            .git
            .github 
